reference:
  test: "data/references/test"
  miniGWG: "data/references/miniGWG"
  megaGMG: "data/references/megaGMG"
  megaGWG: "data/references/megaGWG"

settings:
  benchmarks: true
  debug: true

benchmark_replicates: 3
contexts: ['test', 'miniGWG']
tools: ['utree']
