reference:
  test: "data/references/test"
  miniGWG: "data/references/gmg/miniGWG"
  megaGMG: "data/references/gmg/megaGMG"
  megaGWG: "data/references/gmg/megaGWG"

settings:
  benchmarks: true
  debug: true

benchmark_replicates: 3
contexts: ['test']
