reference:
  test: "data/references/test"
  miniGWG: "data/references/miniGWG"
  megaGMG: "data/references/megaGMG"
  megaGWG: "data/references/megaGWG"
  miniGWG_darth: "data/references/miniGWG_darth"
  miniGWG_darth_lin: "data/references/linear"
  miniGWG_darth_lin_dusted:

redistribute: "data/shogun/database/sheared_bayes.txt"

settings:
  benchmarks: true
  debug: true

benchmark_replicates: 3
contexts: ['test', 'miniGWG']
tools: ['utree']
