reference:
  test: "data/references/test/miniGWG.100"
  miniGWG: "data/references/gmg/miniGWG"
  megaGMG: "data/references/gmg/megaGMG"
  megaGWG: "data/references/gmg/megaGWG"

settings:
  benchmarks: true
  debug: true
