name: analysis_SHOGUN
channels:
  - conda-forge
  - defaults
  - r
  - bioconda
dependencies:
  - python>=3
  - ipython
  - numpy
  - cytoolz
  - pip
  - pandas
  - dwgsim==1.1.11
  - snakemake==3.11.2
  - pip:
    - ipdb
    - "git+https://github.com/knights-lab/NINJA-utils.git"
    - "git+https://github.com/knights-lab/DOJO.git"
    - "git+https://github.com/knights-lab/SHOGUN.git"
