import os
# The configuration file
REF_BASENAMES = expand("{path}/test/{basename}", path = data_path, basename = ["miniGWG.100"])
REFS = [utree_ref_path]

def get_fasta_path(wildcards):
    fasta_path = ""

    basename = wildcards.basename

    if basename.startswith("miniGWG.100"):
        fasta_path = os.path.join(result_path, "gmg", "test")
    elif:
        assert False

    return fasta_path

########################################################################
# INDICES
########################################################################
rule utree_specific_build:
    input:
        fasta = "{basename}.fna",
        tax = "{basename}.tax"
    params:
        input_path = get_fasta_path
    output:
        ctr = "{output_path}/{basename}.ctr",
        utree_log = "{output_path}/{basename}.log",
        time_memory_log = "{output_path}/{basename}.time_mem.log"
#    benchmark:
#        "{output_path}/{sample}.txt"
#    threads: 120
    shell:
        """
        /usr/bin/time -v sh -c 'utree-build {params.input_path}/{input.fasta} {params.input_path}/{input.tax} {wildcards.output_path}/{wildcards.basename}.ubt {threads};
        utree-compress {wildcards.output_path}/{wildcards.basename}.ubt {output.ctr}' >> {output.time_memory_log} 2>&1
        mv {wildcards.output_path}/{wildcards.basename}.ubt.log {output.utree_log}
        rm {wildcards.output_path}/{wildcards.basename}.ubt
        """

########################################################################
# TIME RAM LOG
########################################################################
rule generate_indices_time_and_memory_table:
  input:
    # UTREE
    expand("{ref}/{basename}.time_mem.log", ref = REFS, basename = REF_BASENAMES)
  output:
    expand("{output_path}/{name}_table.txt", output_path = result_path, name = "indices_time_and_memory")
  shell:
    "{script_path}/generate_indices_time_and_memory_table.py {input}.time_mem.log >> {output}"

rule clean:
    shell:
        "rm -rf {OUTPUT_PATH}"
